import Seat from "@/model/Seat";

export default class SeatAll {
    // js 생성자 : constructor(매개변수...) {}
    constructor() {
            new Seat("A1", "N", null),
            new Seat("A2", "N", null),
            new Seat("A3", "N", null),
            new Seat("A4", "N", null),
            new Seat("A5", "N", null),
            new Seat("A6", "N", null),
            new Seat("A7", "N", null),
            new Seat("A8", "N", null),
            new Seat("A9", "N", null),
            new Seat("A10", "N", null),
            new Seat("B1", "N", null),
            new Seat("B2", "N", null),
            new Seat("B3", "N", null),
            new Seat("B4", "N", null),
            new Seat("B5", "N", null),
            new Seat("B6", "N", null),
            new Seat("B7", "N", null),
            new Seat("B8", "N", null),
            new Seat("B9", "N", null),
            new Seat("B10", "N", null),
            new Seat("C1", "N", null),
            new Seat("C2", "N", null),
            new Seat("C3", "N", null),
            new Seat("C4", "N", null),
            new Seat("C5", "N", null),
            new Seat("C6", "N", null),
            new Seat("C7", "N", null),
            new Seat("C8", "N", null),
            new Seat("C9", "N", null),
            new Seat("C10", "N", null),
            new Seat("D1", "N", null),
            new Seat("D2", "N", null),
            new Seat("D3", "N", null),
            new Seat("D4", "N", null),
            new Seat("D5", "N", null),
            new Seat("D6", "N", null),
            new Seat("D7", "N", null),
            new Seat("D8", "N", null),
            new Seat("D9", "N", null),
            new Seat("D10", "N", null),
            new Seat("E1", "N", null),
            new Seat("E2", "N", null),
            new Seat("E3", "N", null),
            new Seat("E4", "N", null),
            new Seat("E5", "N", null),
            new Seat("E6", "N", null),
            new Seat("E7", "N", null),
            new Seat("E8", "N", null),
            new Seat("E9", "N", null),
            new Seat("E10", "N", null),
            new Seat("F1", "N", null),
            new Seat("F2", "N", null),
            new Seat("F3", "N", null),
            new Seat("F4", "N", null),
            new Seat("F5", "N", null),
            new Seat("F6", "N", null),
            new Seat("F7", "N", null),
            new Seat("F8", "N", null),
            new Seat("F9", "N", null)
            new Seat("F10", "N", null)
    }
}