DROP SEQUENCE SQ_USER;
CREATE SEQUENCE SQ_USER
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;

DROP SEQUENCE SQ_ROLE;
CREATE SEQUENCE SQ_ROLE
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;

DROP SEQUENCE SQ_RESERV;
CREATE SEQUENCE SQ_RESERV
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;

DROP SEQUENCE SQ_SCHE;
CREATE SEQUENCE SQ_SCHE
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;

DROP SEQUENCE SQ_NOTICE;
CREATE SEQUENCE SQ_NOTICE
    INCREMENT BY 1 START WITH 1
    MINVALUE 1
    MAXVALUE 99999999;

DROP SEQUENCE SQ_QNA;
CREATE SEQUENCE SQ_QNA START WITH 1 INCREMENT BY 1;

DROP TABLE TB_USER CASCADE CONSTRAINTS;
DROP TABLE TB_ROLE CASCADE CONSTRAINTS;
DROP TABLE TB_USER_ROLE CASCADE CONSTRAINTS;
-- 추가로 작업한 데이터 모델
-- DROP TABLE TB_RESERV CASCADE CONSTRAINTS;
-- DROP TABLE TB_MOVIE CASCADE CONSTRAINTS;
-- DROP TABLE TB_SCHE CASCADE CONSTRAINTS;
-- DROP TABLE TB_THEA CASCADE CONSTRAINTS;
-- DROP TABLE TB_SEAT CASCADE CONSTRAINTS;
DROP TABLE TB_REVIEW CASCADE CONSTRAINTS;
DROP TABLE TB_NOTICE CASCADE CONSTRAINTS;
DROP TABLE TB_QNA CASCADE CONSTRAINTS;

-- 유저 테이블
-- 유저 테이블
CREATE TABLE TB_USER
(
    ID          NUMBER NOT NULL PRIMARY KEY,
    EMAIL       VARCHAR2(1000),
    PASSWORD    VARCHAR2(1000),
    USERNAME    VARCHAR2(1000),
    PHONE       NUMBER DEFAULT NULL,
    YEAR        NUMBER DEFAULT NULL,
    MONTH       NUMBER DEFAULT NULL,
    DAY         NUMBER DEFAULT NULL,
    NAME        VARCHAR2(1000) DEFAULT NULL,
    ANSWER      VARCHAR2(1000) DEFAULT NULL,
    DELETE_YN   VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(255),
    UPDATE_TIME VARCHAR2(255),
    DELETE_TIME VARCHAR2(255)
);
-- 역할 테이블 : ROLE_USER, ROLE_ADMIN
CREATE TABLE TB_ROLE
(
    RID         NUMBER NOT NULL PRIMARY KEY,
    NAME        VARCHAR2(1000) UNIQUE,
    DELETE_YN   VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(255),
    UPDATE_TIME VARCHAR2(255),
    DELETE_TIME VARCHAR2(255)
);
-- 매핑테이블 : TB_USER vs TB_ROLE 연결시켜주는 테이블 ( Many To Many 관계에서 사용 )
CREATE TABLE TB_USER_ROLE
(
    USER_ID NUMBER NOT NULL,
    ROLE_ID NUMBER NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID) -- 복합키 ( 속성 2이상을 조합해서 기본키로 만드는것 )
);
--
-- CREATE TABLE TB_RESERV
-- (
--     RESERVNO    NUMBER NOT NULL PRIMARY KEY,
--     ID          VARCHAR2(20),
--     MOVIECD     NUMBER,
--     SCHENO      NUMBER,
--     CNT         NUMBER,
--     SHEETNO     VARCHAR2(20),
--     PRICE       NUMBER,
--     PAIDDATE    VARCHAR2(50),
--     DELETE_YN   VARCHAR2(1) DEFAULT 'N',
--     INSERT_TIME VARCHAR2(255),
--     UPDATE_TIME VARCHAR2(255),
--     DELETE_TIME VARCHAR2(255)
-- );
--
-- CREATE TABLE TB_MOVIE
-- (
--     MOVIECD      NUMBER NOT NULL PRIMARY KEY,
--     CTITLEKR     VARCHAR2(100),
--     CTITLEEN     VARCHAR2(100),
--     CTITLEOR     VARCHAR2(100),
--     RUNNINGTIME  NUMBER,
--     PRDTYEAR     NUMBER,
--     POURL        VARCHAR2(100),
--     AUDITS       NUMBER,
--     RUNNINGSTATE VARCHAR2(1),
--     DELETE_YN    VARCHAR2(1) DEFAULT 'N',
--     INSERT_TIME  VARCHAR2(255),
--     UPDATE_TIME  VARCHAR2(255),
--     DELETE_TIME  VARCHAR2(255)
-- );
--
-- CREATE TABLE TB_SCHE
-- (
--     SCNO        NUMBER NOT NULL PRIMARY KEY,
--     MOVIECD     NUMBER,
--     THEATERID   VARCHAR2(100),
--     STARTTIME   VARCHAR2(20),
--     ENDTIME     VARCHAR2(20),
--     DELETE_YN   VARCHAR2(1) DEFAULT 'N',
--     INSERT_TIME VARCHAR2(255),
--     UPDATE_TIME VARCHAR2(255),
--     DELETE_TIME VARCHAR2(255)
-- );
--
-- CREATE TABLE TB_THEA
-- (
--     MOVIECD       NUMBER,
--     LOCATIONTITLE VARCHAR2(100),
--     THEATERID     VARCHAR2(5),
--     SEATCNT       NUMBER
-- );
--
-- CREATE TABLE TB_SEAT
-- (
--     THEATERID  VARCHAR2(5),
--     SEAT       VARCHAR2(2),
--     RESRVUID   VARCHAR2(30),
--     STATUSFLAG VARCHAR2(1)
-- );
--
CREATE TABLE TB_REVIEW
(
    RNO         NUMBER NOT NULL PRIMARY KEY,
    MOVIECD     NUMBER,
    MOVIENM     VARCHAR2(1000),
    USERNAME    VARCHAR2(1000),
    CONTENT     VARCHAR2(1000),
    RATING      NUMBER,
    DELETE_YN   VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(255),
    UPDATE_TIME VARCHAR2(255),
    DELETE_TIME VARCHAR2(255)
);

CREATE TABLE TB_NOTICE
(
    NO          NUMBER NOT NULL PRIMARY KEY,
    TYPE        VARCHAR2(1000),
    TITLE       VARCHAR2(1000),
    CONTENT     VARCHAR2(9000),
    REGDATE     VARCHAR2(9000),
    DELETE_YN   VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(255),
    UPDATE_TIME VARCHAR2(255),
    DELETE_TIME VARCHAR2(255)
);

CREATE TABLE TB_QNA
(
    QNO         NUMBER NOT NULL PRIMARY KEY,
    NAME        VARCHAR2(30),
    EMAIL       VARCHAR2(1000),
    PHONE       VARCHAR2(1000),
    TITLE       VARCHAR2(1000),
    CONTENT     VARCHAR2(4000),
    ANSWER      VARCHAR2(4000) DEFAULT NULL,
    DELETE_YN   VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(255),
    UPDATE_TIME VARCHAR2(255),
    DELETE_TIME VARCHAR2(255)
);

COMMIT;